# render.yaml

services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python nukeboton.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN